// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -603630631;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__simple__init_logging_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_logging",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::simple::init_logging())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__simple__init_rust_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_rust",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_stream_sink = <StreamSink<
                crate::dart_spider::link::ToUi,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            let api_config_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::simple::init_rust(api_stream_sink, api_config_path);
                })?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__write_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "write",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_msg = <crate::dart_spider::link::ToProcessor>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::simple::write(api_msg);
                })?;
                Ok(output_ok)
            })())
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<crate::dart_spider::link::ToUi, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::dart_spider::ui::DartUiElement {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <crate::dart_spider::ui::DartUiElementKind>::sse_decode(deserializer);
        let mut var_id = <Option<String>>::sse_decode(deserializer);
        let mut var_datasetIndices = <Vec<u32>>::sse_decode(deserializer);
        let mut var_text = <String>::sse_decode(deserializer);
        let mut var_children =
            <Vec<crate::dart_spider::ui::DartUiElement>>::sse_decode(deserializer);
        let mut var_selectable = <bool>::sse_decode(deserializer);
        return crate::dart_spider::ui::DartUiElement {
            kind: var_kind,
            id: var_id,
            dataset_indices: var_datasetIndices,
            text: var_text,
            children: var_children,
            selectable: var_selectable,
        };
    }
}

impl SseDecode for crate::dart_spider::ui::DartUiElementKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::dart_spider::ui::DartUiElementKind::None,
            1 => crate::dart_spider::ui::DartUiElementKind::Spacer,
            2 => crate::dart_spider::ui::DartUiElementKind::Columns,
            3 => crate::dart_spider::ui::DartUiElementKind::Rows,
            4 => crate::dart_spider::ui::DartUiElementKind::Header,
            5 => crate::dart_spider::ui::DartUiElementKind::Text,
            6 => crate::dart_spider::ui::DartUiElementKind::TextEntry,
            7 => crate::dart_spider::ui::DartUiElementKind::Button,
            _ => unreachable!("Invalid variant for DartUiElementKind: {}", inner),
        };
    }
}

impl SseDecode for crate::dart_spider::ui::DartUiInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::dart_spider::ui::DartUiInput::Click;
            }
            1 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::dart_spider::ui::DartUiInput::Text(var_field0);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::dart_spider::ui::DartUiPage {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_root = <crate::dart_spider::ui::DartUiElement>::sse_decode(deserializer);
        return crate::dart_spider::ui::DartUiPage {
            id: var_id,
            name: var_name,
            root: var_root,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::dart_spider::ui::DartUiElement> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::dart_spider::ui::DartUiElement>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u32>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<(String, String)> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<(String, String)>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for (String, String) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_field0 = <String>::sse_decode(deserializer);
        let mut var_field1 = <String>::sse_decode(deserializer);
        return (var_field0, var_field1);
    }
}

impl SseDecode for crate::dart_spider::link::ToProcessor {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::dart_spider::link::ToProcessor::Pair(var_field0);
            }
            1 => {
                return crate::dart_spider::link::ToProcessor::Unpair;
            }
            2 => {
                return crate::dart_spider::link::ToProcessor::GenerateInvite;
            }
            3 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::dart_spider::link::ToProcessor::AcceptInvite(var_field0);
            }
            4 => {
                let mut var_pageId = <String>::sse_decode(deserializer);
                let mut var_elementId = <String>::sse_decode(deserializer);
                let mut var_datasetIndices = <Vec<u32>>::sse_decode(deserializer);
                let mut var_input = <crate::dart_spider::ui::DartUiInput>::sse_decode(deserializer);
                return crate::dart_spider::link::ToProcessor::Input {
                    page_id: var_pageId,
                    element_id: var_elementId,
                    dataset_indices: var_datasetIndices,
                    input: var_input,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::dart_spider::link::ToUi {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::dart_spider::link::ToUi::SetId(var_field0);
            }
            1 => {
                return crate::dart_spider::link::ToUi::Unpaired;
            }
            2 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::dart_spider::link::ToUi::GeneratedInvite(var_field0);
            }
            3 => {
                let mut var_relations = <Vec<(String, String)>>::sse_decode(deserializer);
                return crate::dart_spider::link::ToUi::Pairs {
                    relations: var_relations,
                };
            }
            4 => {
                let mut var_key = <String>::sse_decode(deserializer);
                let mut var_name = <String>::sse_decode(deserializer);
                return crate::dart_spider::link::ToUi::Base {
                    key: var_key,
                    name: var_name,
                };
            }
            5 => {
                let mut var_msg = <String>::sse_decode(deserializer);
                return crate::dart_spider::link::ToUi::Connecting { msg: var_msg };
            }
            6 => {
                let mut var_msg = <String>::sse_decode(deserializer);
                return crate::dart_spider::link::ToUi::Status { msg: var_msg };
            }
            7 => {
                let mut var_approved = <bool>::sse_decode(deserializer);
                return crate::dart_spider::link::ToUi::Pending {
                    approved: var_approved,
                };
            }
            8 => {
                return crate::dart_spider::link::ToUi::Connected;
            }
            9 => {
                let mut var_pages = <Vec<String>>::sse_decode(deserializer);
                return crate::dart_spider::link::ToUi::SetPageOrder { pages: var_pages };
            }
            10 => {
                let mut var_page = <crate::dart_spider::ui::DartUiPage>::sse_decode(deserializer);
                return crate::dart_spider::link::ToUi::SetPage { page: var_page };
            }
            11 => {
                let mut var_msg = <String>::sse_decode(deserializer);
                let mut var_fatal = <bool>::sse_decode(deserializer);
                return crate::dart_spider::link::ToUi::Error {
                    msg: var_msg,
                    fatal: var_fatal,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__simple__init_logging_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        2 => wire__crate__api__simple__init_rust_impl(ptr, rust_vec_len, data_len),
        3 => wire__crate__api__simple__write_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::dart_spider::ui::DartUiElement {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.id.into_into_dart().into_dart(),
            self.dataset_indices.into_into_dart().into_dart(),
            self.text.into_into_dart().into_dart(),
            self.children.into_into_dart().into_dart(),
            self.selectable.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::dart_spider::ui::DartUiElement
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::dart_spider::ui::DartUiElement>
    for crate::dart_spider::ui::DartUiElement
{
    fn into_into_dart(self) -> crate::dart_spider::ui::DartUiElement {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::dart_spider::ui::DartUiElementKind {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::None => 0.into_dart(),
            Self::Spacer => 1.into_dart(),
            Self::Columns => 2.into_dart(),
            Self::Rows => 3.into_dart(),
            Self::Header => 4.into_dart(),
            Self::Text => 5.into_dart(),
            Self::TextEntry => 6.into_dart(),
            Self::Button => 7.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::dart_spider::ui::DartUiElementKind
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::dart_spider::ui::DartUiElementKind>
    for crate::dart_spider::ui::DartUiElementKind
{
    fn into_into_dart(self) -> crate::dart_spider::ui::DartUiElementKind {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::dart_spider::ui::DartUiInput {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::dart_spider::ui::DartUiInput::Click => [0.into_dart()].into_dart(),
            crate::dart_spider::ui::DartUiInput::Text(field0) => {
                [1.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::dart_spider::ui::DartUiInput
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::dart_spider::ui::DartUiInput>
    for crate::dart_spider::ui::DartUiInput
{
    fn into_into_dart(self) -> crate::dart_spider::ui::DartUiInput {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::dart_spider::ui::DartUiPage {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.root.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::dart_spider::ui::DartUiPage
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::dart_spider::ui::DartUiPage>
    for crate::dart_spider::ui::DartUiPage
{
    fn into_into_dart(self) -> crate::dart_spider::ui::DartUiPage {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::dart_spider::link::ToProcessor {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::dart_spider::link::ToProcessor::Pair(field0) => {
                [0.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::dart_spider::link::ToProcessor::Unpair => [1.into_dart()].into_dart(),
            crate::dart_spider::link::ToProcessor::GenerateInvite => [2.into_dart()].into_dart(),
            crate::dart_spider::link::ToProcessor::AcceptInvite(field0) => {
                [3.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::dart_spider::link::ToProcessor::Input {
                page_id,
                element_id,
                dataset_indices,
                input,
            } => [
                4.into_dart(),
                page_id.into_into_dart().into_dart(),
                element_id.into_into_dart().into_dart(),
                dataset_indices.into_into_dart().into_dart(),
                input.into_into_dart().into_dart(),
            ]
            .into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::dart_spider::link::ToProcessor
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::dart_spider::link::ToProcessor>
    for crate::dart_spider::link::ToProcessor
{
    fn into_into_dart(self) -> crate::dart_spider::link::ToProcessor {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::dart_spider::link::ToUi {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::dart_spider::link::ToUi::SetId(field0) => {
                [0.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::dart_spider::link::ToUi::Unpaired => [1.into_dart()].into_dart(),
            crate::dart_spider::link::ToUi::GeneratedInvite(field0) => {
                [2.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::dart_spider::link::ToUi::Pairs { relations } => {
                [3.into_dart(), relations.into_into_dart().into_dart()].into_dart()
            }
            crate::dart_spider::link::ToUi::Base { key, name } => [
                4.into_dart(),
                key.into_into_dart().into_dart(),
                name.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::dart_spider::link::ToUi::Connecting { msg } => {
                [5.into_dart(), msg.into_into_dart().into_dart()].into_dart()
            }
            crate::dart_spider::link::ToUi::Status { msg } => {
                [6.into_dart(), msg.into_into_dart().into_dart()].into_dart()
            }
            crate::dart_spider::link::ToUi::Pending { approved } => {
                [7.into_dart(), approved.into_into_dart().into_dart()].into_dart()
            }
            crate::dart_spider::link::ToUi::Connected => [8.into_dart()].into_dart(),
            crate::dart_spider::link::ToUi::SetPageOrder { pages } => {
                [9.into_dart(), pages.into_into_dart().into_dart()].into_dart()
            }
            crate::dart_spider::link::ToUi::SetPage { page } => {
                [10.into_dart(), page.into_into_dart().into_dart()].into_dart()
            }
            crate::dart_spider::link::ToUi::Error { msg, fatal } => [
                11.into_dart(),
                msg.into_into_dart().into_dart(),
                fatal.into_into_dart().into_dart(),
            ]
            .into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::dart_spider::link::ToUi
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::dart_spider::link::ToUi>
    for crate::dart_spider::link::ToUi
{
    fn into_into_dart(self) -> crate::dart_spider::link::ToUi {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<crate::dart_spider::link::ToUi, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::dart_spider::ui::DartUiElement {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::dart_spider::ui::DartUiElementKind>::sse_encode(self.kind, serializer);
        <Option<String>>::sse_encode(self.id, serializer);
        <Vec<u32>>::sse_encode(self.dataset_indices, serializer);
        <String>::sse_encode(self.text, serializer);
        <Vec<crate::dart_spider::ui::DartUiElement>>::sse_encode(self.children, serializer);
        <bool>::sse_encode(self.selectable, serializer);
    }
}

impl SseEncode for crate::dart_spider::ui::DartUiElementKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::dart_spider::ui::DartUiElementKind::None => 0,
                crate::dart_spider::ui::DartUiElementKind::Spacer => 1,
                crate::dart_spider::ui::DartUiElementKind::Columns => 2,
                crate::dart_spider::ui::DartUiElementKind::Rows => 3,
                crate::dart_spider::ui::DartUiElementKind::Header => 4,
                crate::dart_spider::ui::DartUiElementKind::Text => 5,
                crate::dart_spider::ui::DartUiElementKind::TextEntry => 6,
                crate::dart_spider::ui::DartUiElementKind::Button => 7,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::dart_spider::ui::DartUiInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::dart_spider::ui::DartUiInput::Click => {
                <i32>::sse_encode(0, serializer);
            }
            crate::dart_spider::ui::DartUiInput::Text(field0) => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(field0, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::dart_spider::ui::DartUiPage {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.name, serializer);
        <crate::dart_spider::ui::DartUiElement>::sse_encode(self.root, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::dart_spider::ui::DartUiElement> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::dart_spider::ui::DartUiElement>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u32>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<(String, String)> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <(String, String)>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for (String, String) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.0, serializer);
        <String>::sse_encode(self.1, serializer);
    }
}

impl SseEncode for crate::dart_spider::link::ToProcessor {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::dart_spider::link::ToProcessor::Pair(field0) => {
                <i32>::sse_encode(0, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::dart_spider::link::ToProcessor::Unpair => {
                <i32>::sse_encode(1, serializer);
            }
            crate::dart_spider::link::ToProcessor::GenerateInvite => {
                <i32>::sse_encode(2, serializer);
            }
            crate::dart_spider::link::ToProcessor::AcceptInvite(field0) => {
                <i32>::sse_encode(3, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::dart_spider::link::ToProcessor::Input {
                page_id,
                element_id,
                dataset_indices,
                input,
            } => {
                <i32>::sse_encode(4, serializer);
                <String>::sse_encode(page_id, serializer);
                <String>::sse_encode(element_id, serializer);
                <Vec<u32>>::sse_encode(dataset_indices, serializer);
                <crate::dart_spider::ui::DartUiInput>::sse_encode(input, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::dart_spider::link::ToUi {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::dart_spider::link::ToUi::SetId(field0) => {
                <i32>::sse_encode(0, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::dart_spider::link::ToUi::Unpaired => {
                <i32>::sse_encode(1, serializer);
            }
            crate::dart_spider::link::ToUi::GeneratedInvite(field0) => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::dart_spider::link::ToUi::Pairs { relations } => {
                <i32>::sse_encode(3, serializer);
                <Vec<(String, String)>>::sse_encode(relations, serializer);
            }
            crate::dart_spider::link::ToUi::Base { key, name } => {
                <i32>::sse_encode(4, serializer);
                <String>::sse_encode(key, serializer);
                <String>::sse_encode(name, serializer);
            }
            crate::dart_spider::link::ToUi::Connecting { msg } => {
                <i32>::sse_encode(5, serializer);
                <String>::sse_encode(msg, serializer);
            }
            crate::dart_spider::link::ToUi::Status { msg } => {
                <i32>::sse_encode(6, serializer);
                <String>::sse_encode(msg, serializer);
            }
            crate::dart_spider::link::ToUi::Pending { approved } => {
                <i32>::sse_encode(7, serializer);
                <bool>::sse_encode(approved, serializer);
            }
            crate::dart_spider::link::ToUi::Connected => {
                <i32>::sse_encode(8, serializer);
            }
            crate::dart_spider::link::ToUi::SetPageOrder { pages } => {
                <i32>::sse_encode(9, serializer);
                <Vec<String>>::sse_encode(pages, serializer);
            }
            crate::dart_spider::link::ToUi::SetPage { page } => {
                <i32>::sse_encode(10, serializer);
                <crate::dart_spider::ui::DartUiPage>::sse_encode(page, serializer);
            }
            crate::dart_spider::link::ToUi::Error { msg, fatal } => {
                <i32>::sse_encode(11, serializer);
                <String>::sse_encode(msg, serializer);
                <bool>::sse_encode(fatal, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
