// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.36.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'dart_spider/link.dart';
import 'dart_spider/ui.dart';
import 'frb_generated.io.dart' if (dart.library.html) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.0.0-dev.36';

  @override
  int get rustContentHash => -603630631;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_spider_gui',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiSimpleInitLogging({dynamic hint});

  Stream<ToUi> crateApiSimpleInitRust(
      {required String configPath, dynamic hint});

  void crateApiSimpleWrite({required ToProcessor msg, dynamic hint});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiSimpleInitLogging({dynamic hint}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleInitLoggingConstMeta,
      argValues: [],
      apiImpl: this,
      hint: hint,
    ));
  }

  TaskConstMeta get kCrateApiSimpleInitLoggingConstMeta => const TaskConstMeta(
        debugName: "init_logging",
        argNames: [],
      );

  @override
  Stream<ToUi> crateApiSimpleInitRust(
      {required String configPath, dynamic hint}) {
    final streamSink = RustStreamSink<ToUi>();
    handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_StreamSink_to_ui_Sse(streamSink, serializer);
        sse_encode_String(configPath, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleInitRustConstMeta,
      argValues: [streamSink, configPath],
      apiImpl: this,
      hint: hint,
    ));
    return streamSink.stream;
  }

  TaskConstMeta get kCrateApiSimpleInitRustConstMeta => const TaskConstMeta(
        debugName: "init_rust",
        argNames: ["streamSink", "configPath"],
      );

  @override
  void crateApiSimpleWrite({required ToProcessor msg, dynamic hint}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_to_processor(msg, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleWriteConstMeta,
      argValues: [msg],
      apiImpl: this,
      hint: hint,
    ));
  }

  TaskConstMeta get kCrateApiSimpleWriteConstMeta => const TaskConstMeta(
        debugName: "write",
        argNames: ["msg"],
      );

  @protected
  RustStreamSink<ToUi> dco_decode_StreamSink_to_ui_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DartUiInput dco_decode_box_autoadd_dart_ui_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_dart_ui_input(raw);
  }

  @protected
  DartUiPage dco_decode_box_autoadd_dart_ui_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_dart_ui_page(raw);
  }

  @protected
  ToProcessor dco_decode_box_autoadd_to_processor(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_to_processor(raw);
  }

  @protected
  DartUiElement dco_decode_dart_ui_element(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return DartUiElement(
      kind: dco_decode_dart_ui_element_kind(arr[0]),
      id: dco_decode_opt_String(arr[1]),
      datasetIndices: dco_decode_list_prim_u_32_strict(arr[2]),
      text: dco_decode_String(arr[3]),
      children: dco_decode_list_dart_ui_element(arr[4]),
      selectable: dco_decode_bool(arr[5]),
    );
  }

  @protected
  DartUiElementKind dco_decode_dart_ui_element_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DartUiElementKind.values[raw as int];
  }

  @protected
  DartUiInput dco_decode_dart_ui_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return DartUiInput_Click();
      case 1:
        return DartUiInput_Text(
          dco_decode_String(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  DartUiPage dco_decode_dart_ui_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DartUiPage(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      root: dco_decode_dart_ui_element(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<DartUiElement> dco_decode_list_dart_ui_element(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_dart_ui_element).toList();
  }

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_String(arr[0]),
      dco_decode_String(arr[1]),
    );
  }

  @protected
  ToProcessor dco_decode_to_processor(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ToProcessor_Pair(
          dco_decode_String(raw[1]),
        );
      case 1:
        return ToProcessor_Unpair();
      case 2:
        return ToProcessor_GenerateInvite();
      case 3:
        return ToProcessor_Input(
          pageId: dco_decode_String(raw[1]),
          elementId: dco_decode_String(raw[2]),
          datasetIndices: dco_decode_list_prim_u_32_strict(raw[3]),
          input: dco_decode_box_autoadd_dart_ui_input(raw[4]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  ToUi dco_decode_to_ui(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ToUi_SetId(
          dco_decode_String(raw[1]),
        );
      case 1:
        return ToUi_Unpaired();
      case 2:
        return ToUi_GeneratedInvite(
          dco_decode_String(raw[1]),
        );
      case 3:
        return ToUi_Pairs(
          relations: dco_decode_list_record_string_string(raw[1]),
        );
      case 4:
        return ToUi_Base(
          key: dco_decode_String(raw[1]),
          name: dco_decode_String(raw[2]),
        );
      case 5:
        return ToUi_Connecting(
          msg: dco_decode_String(raw[1]),
        );
      case 6:
        return ToUi_Status(
          msg: dco_decode_String(raw[1]),
        );
      case 7:
        return ToUi_Pending(
          approved: dco_decode_bool(raw[1]),
        );
      case 8:
        return ToUi_Connected();
      case 9:
        return ToUi_SetPageOrder(
          pages: dco_decode_list_String(raw[1]),
        );
      case 10:
        return ToUi_SetPage(
          page: dco_decode_box_autoadd_dart_ui_page(raw[1]),
        );
      case 11:
        return ToUi_Error(
          msg: dco_decode_String(raw[1]),
          fatal: dco_decode_bool(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  RustStreamSink<ToUi> sse_decode_StreamSink_to_ui_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DartUiInput sse_decode_box_autoadd_dart_ui_input(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_dart_ui_input(deserializer));
  }

  @protected
  DartUiPage sse_decode_box_autoadd_dart_ui_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_dart_ui_page(deserializer));
  }

  @protected
  ToProcessor sse_decode_box_autoadd_to_processor(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_to_processor(deserializer));
  }

  @protected
  DartUiElement sse_decode_dart_ui_element(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_dart_ui_element_kind(deserializer);
    var var_id = sse_decode_opt_String(deserializer);
    var var_datasetIndices = sse_decode_list_prim_u_32_strict(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_children = sse_decode_list_dart_ui_element(deserializer);
    var var_selectable = sse_decode_bool(deserializer);
    return DartUiElement(
        kind: var_kind,
        id: var_id,
        datasetIndices: var_datasetIndices,
        text: var_text,
        children: var_children,
        selectable: var_selectable);
  }

  @protected
  DartUiElementKind sse_decode_dart_ui_element_kind(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return DartUiElementKind.values[inner];
  }

  @protected
  DartUiInput sse_decode_dart_ui_input(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return DartUiInput_Click();
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return DartUiInput_Text(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  DartUiPage sse_decode_dart_ui_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_root = sse_decode_dart_ui_element(deserializer);
    return DartUiPage(id: var_id, name: var_name, root: var_root);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<DartUiElement> sse_decode_list_dart_ui_element(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DartUiElement>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_dart_ui_element(deserializer));
    }
    return ans_;
  }

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (String, String) sse_decode_record_string_string(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  ToProcessor sse_decode_to_processor(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return ToProcessor_Pair(var_field0);
      case 1:
        return ToProcessor_Unpair();
      case 2:
        return ToProcessor_GenerateInvite();
      case 3:
        var var_pageId = sse_decode_String(deserializer);
        var var_elementId = sse_decode_String(deserializer);
        var var_datasetIndices = sse_decode_list_prim_u_32_strict(deserializer);
        var var_input = sse_decode_box_autoadd_dart_ui_input(deserializer);
        return ToProcessor_Input(
            pageId: var_pageId,
            elementId: var_elementId,
            datasetIndices: var_datasetIndices,
            input: var_input);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  ToUi sse_decode_to_ui(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return ToUi_SetId(var_field0);
      case 1:
        return ToUi_Unpaired();
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return ToUi_GeneratedInvite(var_field0);
      case 3:
        var var_relations = sse_decode_list_record_string_string(deserializer);
        return ToUi_Pairs(relations: var_relations);
      case 4:
        var var_key = sse_decode_String(deserializer);
        var var_name = sse_decode_String(deserializer);
        return ToUi_Base(key: var_key, name: var_name);
      case 5:
        var var_msg = sse_decode_String(deserializer);
        return ToUi_Connecting(msg: var_msg);
      case 6:
        var var_msg = sse_decode_String(deserializer);
        return ToUi_Status(msg: var_msg);
      case 7:
        var var_approved = sse_decode_bool(deserializer);
        return ToUi_Pending(approved: var_approved);
      case 8:
        return ToUi_Connected();
      case 9:
        var var_pages = sse_decode_list_String(deserializer);
        return ToUi_SetPageOrder(pages: var_pages);
      case 10:
        var var_page = sse_decode_box_autoadd_dart_ui_page(deserializer);
        return ToUi_SetPage(page: var_page);
      case 11:
        var var_msg = sse_decode_String(deserializer);
        var var_fatal = sse_decode_bool(deserializer);
        return ToUi_Error(msg: var_msg, fatal: var_fatal);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_StreamSink_to_ui_Sse(
      RustStreamSink<ToUi> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
                decodeSuccessData: sse_decode_to_ui, decodeErrorData: null)),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_dart_ui_input(
      DartUiInput self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_dart_ui_input(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_dart_ui_page(
      DartUiPage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_dart_ui_page(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_to_processor(
      ToProcessor self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_to_processor(self, serializer);
  }

  @protected
  void sse_encode_dart_ui_element(
      DartUiElement self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_dart_ui_element_kind(self.kind, serializer);
    sse_encode_opt_String(self.id, serializer);
    sse_encode_list_prim_u_32_strict(self.datasetIndices, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_list_dart_ui_element(self.children, serializer);
    sse_encode_bool(self.selectable, serializer);
  }

  @protected
  void sse_encode_dart_ui_element_kind(
      DartUiElementKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_dart_ui_input(DartUiInput self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case DartUiInput_Click():
        sse_encode_i_32(0, serializer);
      case DartUiInput_Text(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_dart_ui_page(DartUiPage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_dart_ui_element(self.root, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_dart_ui_element(
      List<DartUiElement> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_dart_ui_element(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_32_strict(
      Uint32List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_string(
      List<(String, String)> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_record_string_string(
      (String, String) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_to_processor(ToProcessor self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ToProcessor_Pair(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case ToProcessor_Unpair():
        sse_encode_i_32(1, serializer);
      case ToProcessor_GenerateInvite():
        sse_encode_i_32(2, serializer);
      case ToProcessor_Input(
          pageId: final pageId,
          elementId: final elementId,
          datasetIndices: final datasetIndices,
          input: final input
        ):
        sse_encode_i_32(3, serializer);
        sse_encode_String(pageId, serializer);
        sse_encode_String(elementId, serializer);
        sse_encode_list_prim_u_32_strict(datasetIndices, serializer);
        sse_encode_box_autoadd_dart_ui_input(input, serializer);
    }
  }

  @protected
  void sse_encode_to_ui(ToUi self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ToUi_SetId(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case ToUi_Unpaired():
        sse_encode_i_32(1, serializer);
      case ToUi_GeneratedInvite(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
      case ToUi_Pairs(relations: final relations):
        sse_encode_i_32(3, serializer);
        sse_encode_list_record_string_string(relations, serializer);
      case ToUi_Base(key: final key, name: final name):
        sse_encode_i_32(4, serializer);
        sse_encode_String(key, serializer);
        sse_encode_String(name, serializer);
      case ToUi_Connecting(msg: final msg):
        sse_encode_i_32(5, serializer);
        sse_encode_String(msg, serializer);
      case ToUi_Status(msg: final msg):
        sse_encode_i_32(6, serializer);
        sse_encode_String(msg, serializer);
      case ToUi_Pending(approved: final approved):
        sse_encode_i_32(7, serializer);
        sse_encode_bool(approved, serializer);
      case ToUi_Connected():
        sse_encode_i_32(8, serializer);
      case ToUi_SetPageOrder(pages: final pages):
        sse_encode_i_32(9, serializer);
        sse_encode_list_String(pages, serializer);
      case ToUi_SetPage(page: final page):
        sse_encode_i_32(10, serializer);
        sse_encode_box_autoadd_dart_ui_page(page, serializer);
      case ToUi_Error(msg: final msg, fatal: final fatal):
        sse_encode_i_32(11, serializer);
        sse_encode_String(msg, serializer);
        sse_encode_bool(fatal, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
