[package]
name = "rust_lib_spider_gui"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = { version = "=2.11.1", features = ["log"] }
tokio = { version = "1", features = ["full"] }
tracing-core = "0.1.35"
rand = "0.9.2"
spider_client = { git = "https://github.com/Ocelmot/spider", rev = "3ac3afd3d00237af8b836d828b902a9fdb8f6adf", features=["transport_iroh"]}

serde_json = "1.0.73"
serde = { version = "1.0.132", features = ["derive"] }
log = "0.4.21"
env_logger = "0.11.5"

# Dependencies for Android
[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21.1"
android_logger = "0.15.1"

# Dependencies for IOS
[target.'cfg(target_os = "ios")'.dependencies]
oslog = {version = "0.2.0"}
