// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'ui.dart';
part 'link.freezed.dart';

@freezed
sealed class ToProcessor with _$ToProcessor {
  const ToProcessor._();

  const factory ToProcessor.pair(
    String field0,
  ) = ToProcessor_Pair;
  const factory ToProcessor.unpair() = ToProcessor_Unpair;
  const factory ToProcessor.generateInvite() = ToProcessor_GenerateInvite;
  const factory ToProcessor.acceptInvite(
    String field0,
  ) = ToProcessor_AcceptInvite;
  const factory ToProcessor.input({
    required String pageId,
    required String elementId,
    required Uint32List datasetIndices,
    required DartUiInput input,
  }) = ToProcessor_Input;
}

@freezed
sealed class ToUi with _$ToUi {
  const ToUi._();

  const factory ToUi.setId(
    String field0,
  ) = ToUi_SetId;
  const factory ToUi.unpaired() = ToUi_Unpaired;
  const factory ToUi.generatedInvite(
    String field0,
  ) = ToUi_GeneratedInvite;
  const factory ToUi.pairs({
    /// first string is name, second is base64 of its key
    required List<(String, String)> relations,
  }) = ToUi_Pairs;
  const factory ToUi.base({
    required String key,
    required String name,
  }) = ToUi_Base;
  const factory ToUi.connecting({
    required String msg,
  }) = ToUi_Connecting;
  const factory ToUi.status({
    required String msg,
  }) = ToUi_Status;
  const factory ToUi.pending({
    required bool approved,
  }) = ToUi_Pending;
  const factory ToUi.connected() = ToUi_Connected;
  const factory ToUi.setPageOrder({
    required List<String> pages,
  }) = ToUi_SetPageOrder;
  const factory ToUi.setPage({
    required DartUiPage page,
  }) = ToUi_SetPage;
  const factory ToUi.error({
    required String msg,
    required bool fatal,
  }) = ToUi_Error;
}
