// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'ui.freezed.dart';

class DartUiElement {
  final DartUiElementKind kind;
  final String? id;
  final Uint32List datasetIndices;
  final String text;
  final List<DartUiElement> children;
  final bool selectable;

  const DartUiElement({
    required this.kind,
    this.id,
    required this.datasetIndices,
    required this.text,
    required this.children,
    required this.selectable,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      id.hashCode ^
      datasetIndices.hashCode ^
      text.hashCode ^
      children.hashCode ^
      selectable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DartUiElement &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          id == other.id &&
          datasetIndices == other.datasetIndices &&
          text == other.text &&
          children == other.children &&
          selectable == other.selectable;
}

enum DartUiElementKind {
  none,
  spacer,
  columns,
  rows,
  header,
  text,
  textEntry,
  button,
  ;
}

@freezed
sealed class DartUiInput with _$DartUiInput {
  const DartUiInput._();

  const factory DartUiInput.click() = DartUiInput_Click;
  const factory DartUiInput.text(
    String field0,
  ) = DartUiInput_Text;
}

class DartUiPage {
  final String id;
  final String name;
  final DartUiElement root;

  const DartUiPage({
    required this.id,
    required this.name,
    required this.root,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ root.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DartUiPage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          root == other.root;
}
