// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

BleUuids bleUuids() => RustLib.instance.api.crateApiAttachBleUuids();

bool isSupported({required NetworkSecurityType secType}) =>
    RustLib.instance.api.crateApiAttachIsSupported(secType: secType);

String securityTypeName({required NetworkSecurityType secType}) =>
    RustLib.instance.api.crateApiAttachSecurityTypeName(secType: secType);

(AttachSalt, AttachNonce)? parseNonce({required List<int> data}) =>
    RustLib.instance.api.crateApiAttachParseNonce(data: data);

AttachKey? generateKey(
        {required String hardwareCode, required AttachSalt salt}) =>
    RustLib.instance.api
        .crateApiAttachGenerateKey(hardwareCode: hardwareCode, salt: salt);

bool validateHardwareCode({required String hardwareCode}) =>
    RustLib.instance.api
        .crateApiAttachValidateHardwareCode(hardwareCode: hardwareCode);

AttachSecurityType openSecurityType() =>
    RustLib.instance.api.crateApiAttachOpenSecurityType();

AttachSecurityType wpa2SecurityType({required String pass}) =>
    RustLib.instance.api.crateApiAttachWpa2SecurityType(pass: pass);

AttachSecurityType wpa3SecurityType({required String pass}) =>
    RustLib.instance.api.crateApiAttachWpa3SecurityType(pass: pass);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AttachDetails>>
abstract class AttachDetails implements RustOpaqueInterface {
  static AttachDetails? create(
          {required List<int> ssid,
          required AttachSecurityType secType,
          required bool hidden}) =>
      RustLib.instance.api.crateApiAttachAttachDetailsCreate(
          ssid: ssid, secType: secType, hidden: hidden);

  Uint8List pack({required AttachKey key, required AttachNonce nonce});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AttachKey>>
abstract class AttachKey implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AttachNonce>>
abstract class AttachNonce implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AttachSalt>>
abstract class AttachSalt implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AttachSecurityType>>
abstract class AttachSecurityType implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AttachStatus>>
abstract class AttachStatus implements RustOpaqueInterface {
  static AttachStatus? fromBytes({required List<int> bytes}) =>
      RustLib.instance.api.crateApiAttachAttachStatusFromBytes(bytes: bytes);

  StatusKind kind();

  String text();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NetworkDetails>>
abstract class NetworkDetails implements RustOpaqueInterface {
  static NetworkDetails? fromBytes({required List<int> bytes}) =>
      RustLib.instance.api.crateApiAttachNetworkDetailsFromBytes(bytes: bytes);

  NetworkSecurityType secType();

  Uint8List ssid();

  int strength();
}

class BleUuids {
  final String base;
  final String status;
  final String networks;
  final String nonce;
  final String attach;

  const BleUuids({
    required this.base,
    required this.status,
    required this.networks,
    required this.nonce,
    required this.attach,
  });

  @override
  int get hashCode =>
      base.hashCode ^
      status.hashCode ^
      networks.hashCode ^
      nonce.hashCode ^
      attach.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BleUuids &&
          runtimeType == other.runtimeType &&
          base == other.base &&
          status == other.status &&
          networks == other.networks &&
          nonce == other.nonce &&
          attach == other.attach;
}

enum NetworkSecurityType {
  unknown,
  open,
  wep,
  wpaPsk,
  wpa3Sae,
  enterprise,
  ;
}

enum StatusKind {
  unknown,
  ready,
  attaching,
  attached,
  retry,
  notFound,
  invalidCredentials,
  noAddress,
  systemError,
  ;
}
