// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../dart_spider/link.dart';
import '../dart_spider/ui.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Stream<ToUi> initRust({required String configPath}) =>
    RustLib.instance.api.crateApiMainInitRust(configPath: configPath);

void write({required ToProcessor msg}) =>
    RustLib.instance.api.crateApiMainWrite(msg: msg);

Future<bool> initLogging() => RustLib.instance.api.crateApiMainInitLogging();
