// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../dart_spider/link.dart';
import '../dart_spider/ui.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

///frb_marker: #[frb(init)]
Future<void> initApp() => RustLib.instance.api.crateApiSimpleInitApp();

///frb_marker: #[frb(sync)]
Stream<ToUi> initRust({required String configPath}) =>
    RustLib.instance.api.crateApiSimpleInitRust(configPath: configPath);

///frb_marker: #[frb(sync)]
Future<void> write({required ToProcessor msg}) =>
    RustLib.instance.api.crateApiSimpleWrite(msg: msg);
