// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.36.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../dart_spider/link.dart';
import '../dart_spider/ui.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Stream<ToUi> initRust({required String configPath, dynamic hint}) =>
    RustLib.instance.api
        .crateApiSimpleInitRust(configPath: configPath, hint: hint);

void write({required ToProcessor msg, dynamic hint}) =>
    RustLib.instance.api.crateApiSimpleWrite(msg: msg, hint: hint);
